Trying to copy stuff from null buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,19 +2,21 @@
 
 ####### Configure environment
 
-set -e            # fail fast
-set -o pipefail   # do not ignore exit codes when piping output
-set -o posix      # more strict failures in subshells
+# set -e            # fail fast
+#set -o pipefail   # do not ignore exit codes when piping output
+#set -o posix      # more strict failures in subshells
 # set -x          # enable debugging
 
-bp_version="64"
+#bp_version="64"
 
 # Configure directories
-build_dir=$1
-cache_dir=$2
-env_dir=$3
-echo "Removing $2 contents."
-rm -rfv $2/*
+#build_dir=$1
+#cache_dir=$2
+#env_dir=$3
+#echo "Removing $2 contents."
+#rm -rfv $2/*
 
+echo "-----> Nothing to do."
+ 
 
 ####### Build the project's dependencies
