updated existing compile cf

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,20 @@
-#!/bin/bash
-# bin/compile <build-dir> <cache-dir>
+#!/usr/bin/env bash
 
+####### Configure environment
+
+set -e            # fail fast
+set -o pipefail   # do not ignore exit codes when piping output
+set -o posix      # more strict failures in subshells
+# set -x          # enable debugging
+
+bp_version="64"
+
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_dir=$3
 echo "Removing $2 contents."
 rm -rfv $2/*
+
+
+####### Build the project's dependencies
